name: Prepare tag
on:
  push:
    tags: '*'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer, php-scoper, phpcbf

      - name: Install Composer dependencies in build
        run: composer install --working-dir=build --no-dev --no-interaction

      - name: Run PHP-Scoper
        run: php-scoper --config=config/scoper.php --output-dir=build

      - name: Merge scoped files
        run: mv -f build/* . && rm -rf build


      - name: Dump autoload
        run: composer dump-autoload --classmap-authoritative -o

      - name: Format Scoped codes
        run: phpcbf build -q -n --standard="PSR12,PSR1" || true
