name: 🚀 Release to WordPress.org plugins repo
on:
  release:
    types: [published, edited]
jobs:
  tag:
    name: 🎉 New Release
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🚀 WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
