name: 🚀 Release the plugin
on:
  release:
    types: [released]
jobs:
  build-release:
    name: 🎉 New Release
    runs-on: ubuntu-20.04

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer, php-scoper, phpcbf, wp-cli

      - name: Install Composer dependencies in build
        run: composer install --no-dev --no-interaction

      - name: Run PHP-Scoper
        run: php-scoper add-prefix --config=config/scoper.php --output-dir=build

      - name: Merge scoped files
        run: cp -r ./build/* . && rm -rf build

      - name: Dump autoload
        run: composer dump-autoload --classmap-authoritative -o

      - name: Format Scoped codes
        run: phpcbf build -q -n --standard="PSR12,PSR1" || true

      - name: Install WP-CLI dist-archive
        run: wp package install wp-cli/dist-archive-command

      - name: Create ZIP file
        run: wp dist-archive . ./${{ github.event.release.name }}.zip --plugin-dirname=product-specifications

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./${{ github.event.release.name }}.zip"
          asset_name: ${{ github.event.release.name }}.zip
          asset_content_type: application/zip

      - name: 🚀 Deploy plugin to wordpress.org
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
